config/routes.rb
Ghog711::Application.routes.draw do
  resources :albums
  resources :photos
  resources :users
  resources :sessions
  root :to => 'albums#index'
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  attr_accessible :title, :user_id
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  attr_accessible :album_id, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :albums
  attr_accessible :name, :password

  def self.authenticate(name, password)
    # load the user based on the name
    u = User.find(:first, :conditions => {:name => name})

    # check that the user password matches what is in the database 
    if u and u.password == password
      return u
    end
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
  end
  
  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def edit
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(params[:album])

    if @album.save
      redirect_to @album, notice: 'Album was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @album = Album.find(params[:id])

    if @album.update_attributes(params[:album])
      redirect_to @album, notice: 'Album was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def create
    @photo = Photo.new(params[:photo])

    if @photo.save
      redirect_to @photo, notice: 'Photo was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @photo = Photo.find(params[:id])

    if @photo.update_attributes(params[:photo])
      redirect_to @photo, notice: 'Photo was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    
    # attempt to authenticate user based on the user/password params
    user = User.authenticate(params[:name], params[:password])

    if user
      # if so, store the current_user and redirect to homepage
      session[:current_user] = user.id
      redirect_to albums_path, notice: "welcome back #{user.name}"
    else
      # else say they failed and let them try again
      redirect_to new_session_path, notice: 'invalid name/password'
    end
  end
  
  def new
  end
  
  def destroy
    session.clear
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    if session[:current_user]
      User.find(session[:current_user])
    end
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/_formEdit.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  </br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>
</br>
<%= render 'formEdit' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Albums</h1>
</br>
    <table class="table table-striped table-condensed">
    <tr>
      <th>Title</th>
      <th>User Name</th>
      <th></th>
      <th></th>
    </tr>

  <% @albums.each do |album| %>
    <tr>
      <td><%= link_to album.title, album %></td>
      <td><%= link_to album.user.name, album.user %></td>
      <td><%= link_to 'Edit', edit_album_path(album) %></td>
      <td><%= link_to 'Delete Album', album, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p>
  <b>Title:</b>
  <%= @album.title %>
</p>

<p>
  <b>Uploaded by:</b>
  <%= @album.user.name %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ghog711</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Groundhog</a>
          <div class="nav-collapse">
          </div>
        </div>
      </div>
    </div>

    <div class="container">
        <% if current_user %>
          Hello <%= current_user.name %>
          <%= link_to "Logout", session_path('logout'), method: 'delete' %>
        <% else %>
          <%= link_to "Login", new_session_path %> |
          <%= link_to "Signup", new_user_path  %>
        <% end %>
      
      <div class="row">
        <div class="span9">
          <div class="well">
            <% if notice %>
              <p class="alert alert-info"><%= notice %></p>
            <% end %>
            <%= yield %>
          </div>
        </div>

        <div class="span3">
          <h3>About Groundhog</h3>
          <p>This is a simple photo uploading site, that will have various features added to create future versions. The purpose of this is to familiarize myself with rails, and all that you can do with the framework. For more information on the project see: <a href="https://github.com/chadthebad/meta-album">github.com/chadthebad/meta-album</a></p>        
        </div>
      </div>
    </div>
    
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :album_id %>
    <%= f.number_field :album_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>
</br>
<table>
  <tr>
    <th>Title</th>
    <th>Album</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.title %></td>
    <td><%= photo.album_id %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>
</br>
<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p>
  <b>Title:</b>
  <%= @photo.title %>
</p>

<p>
  <b>Album:</b>
  <%= @photo.album_id %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  </br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>
<br/>
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
</br>
<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Delete', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

</br>
<table class="table table-striped table-condensed">
  <tr>
    <th>Albums</th>
    <th></th>
    <th></th>

  <% @user.albums.each do |album| %>
    <tr>
      <td><%= link_to album.title, album %></td>
      <td><%= link_to 'Edit', edit_album_path(album) %></td>
      <td><%= link_to 'Delete Album', album, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>